name: CI Tests using Docker 
on: [push]
jobs:
    test-create-ks-iso:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
        - name: Build the Docker image
          run: docker build . --file Dockerfile --platform linux/amd64 --tag create-ks-iso:ci-test
        - run: echo "Docker build status is ${{ job.status }}."
        - name: Run with script defaults
          run:  docker run create-ks-iso:ci-test

